name: wizard
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  mime_type: 0.3.2
  flutter_dropzone: 1.0.9
  file_picker: 2.0.12
  markdown_widget: 1.2.6
  get: 
  firebase_auth: 
  firebase_core: 
  cloud_firestore: 
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0

dev_dependencies:
  lint: 1.3.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/Amp.png
    - assets/README.md