name: wizard
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"


dependencies:
  loading_indicator: 1.2.0
  flutter_markdown: 0.5.0
  url_launcher: 5.7.10
  get: 3.16.1
  mime_type: 0.3.2
  flutter_dropzone: 1.0.9
  file_picker: 2.0.12
  markdown_widget: 1.2.6
  firebase_auth: 
  firebase_core: 
  cloud_firestore: 
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0

dev_dependencies:
  lint: 1.3.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/Amp.png