name: wizard
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  markdown_widget: 1.2.5
  get: 
  firebase_auth: 
  firebase_core: 
  cloud_firestore: 
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0

dev_dependencies:
  lint: 1.3.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/pic1.jpg
    - assets/README.md